/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#b5b1af',
        'secondary-dim': '#803f49',
        'primary-fixed': '#ffc8b5',
        'surface-variant': '#e7e1df',
        'error-dim': '#70030f',
        'tertiary-fixed': '#e1f3ff',
        'secondary-container': '#ffd9dc',
        'primary-dim': '#714a3b',
        'secondary-fixed-dim': '#ffc6cc',
        'inverse-primary': '#ffc8b5',
        'surface-container': '#f2edea',
        primary: '#7e5546',
        'on-secondary': '#fff7f7',
        background: '#fdf8f6',
        'on-error': '#fff7f6',
        'on-secondary-container': '#7e3e48',
        'tertiary-dim': '#45555f',
        'on-tertiary-fixed-variant': '#566770',
        'tertiary-container': '#e1f3ff',
        'on-tertiary-fixed': '#394a53',
        'on-error-container': '#65000b',
        secondary: '#8e4b55',
        outline: '#7d7a78',
        'surface-tint': '#7e5546',
        'primary-container': '#ffc8b5',
        'on-surface-variant': '#615e5c',
        'on-primary-fixed-variant': '#70493b',
        'error-container': '#f56965',
        'on-secondary-fixed-variant': '#8a4851',
        'surface-bright': '#fdf8f6',
        'on-tertiary': '#f3faff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ece7e4',
        'on-primary': '#fff7f5',
        tertiary: '#50616b',
        'on-primary-container': '#654032',
        'surface-container-low': '#f8f2f0',
        error: '#ac3434',
        surface: '#fdf8f6',
        'on-primary-fixed': '#502d20',
        'surface-container-highest': '#e7e1df',
        'tertiary-fixed-dim': '#d3e5f1',
        'inverse-surface': '#0f0e0d',
        'on-background': '#343230',
        'secondary-fixed': '#ffd9dc',
        'on-surface': '#343230',
        'on-tertiary-container': '#4b5c66',
        'on-secondary-fixed': '#682c36',
        'surface-dim': '#ded9d6',
        'inverse-on-surface': '#a09c9a',
        'primary-fixed-dim': '#f0bba8',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
